#!/bin/bash
# Copyright (c) 2021, Xilinx®.
# Author: Víctor Mayoral Vilches <victorma@xilinx.com>
#
# ROS 2 toolchain template targeting ZCU102 sample
#
# NOTE: DO NOT EDIT THIS FILE

# Arguments:
#  - $1: firmware directory, resulting toolchain should be here
#  - $2: vitis directory, refer to "xilinx_vitis" package for details
#  - $3: root of the install directory

cat << EOF > $1/toolchain.cmake
#
# File autogenerated. Do not edit.
#

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_VERBOSE_MAKEFILE:BOOL ON) 

# Specify the cross compilers
set(CMAKE_C_COMPILER $2/cc/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER $2/cc/bin/aarch64-linux-gnu-g++)

# Specify the target file system
set(CMAKE_SYSROOT $1/sysroots/aarch64-xilinx-linux)

set(CMAKE_FIND_ROOT_PATH $3)
set(CMAKE_INSTALL_RPATH 
	${CMAKE_SYSROOT}/usr/lib
   )
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Specify the python SOABI
set(PYTHON_SOABI cpython-37m-aarch64-linux-gnu)

# This assumes that pthread will be available on the target system
# (this emulates that the return of the TRY_RUN is a return code "0")
set(THREADS_PTHREAD_ARG "0"
  CACHE STRING "Result from TRY_RUN" FORCE)

EOF
