#    ____  ____
#   /   /\/   /
#  /___/  \  /   Copyright (c) 2021, Xilinx®.
#  \   \   \/    Author: Víctor Mayoral Vilches <victorma@xilinx.com>
#   \   \
#   /   /
#  /___/   /\
#  \   \  /  \
#   \___\/\___\
#
# ROS 2 custom toolchain targeting ZCU102 sample
#
# NOTE: DO NOT USE THIS FILE. Use the autogenerated one
# NOTE 2: paths are hardcoded

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_VERBOSE_MAKEFILE:BOOL ON)  # pushed to here, instead of as within --cmake-args

set(FIRMWARE_DIR /home/erle/XRS/ros2_ws/build/firmware)
set(VITIS /home/erle/XRS/ros2_ws/build/vitis)
set(WS /home/erle/XRS/ros2_ws)

# Specify the cross compiler
set(CMAKE_C_COMPILER /tools/Xilinx/Vitis/2020.2/gnu/aarch64/lin/aarch64-linux/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /tools/Xilinx/Vitis/2020.2/gnu/aarch64/lin/aarch64-linux/bin/aarch64-linux-gnu-g++)

# Specify the target file system
set(CMAKE_SYSROOT /home/erle/XRS/firmware/sysroots/aarch64-xilinx-linux)
set(CMAKE_FIND_ROOT_PATH /home/erle/XRS/ros2_ws/install)

set(CMAKE_INSTALL_RPATH 
	${CMAKE_SYSROOT}/usr/lib
   )
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Specify the python SOABI
set(PYTHON_SOABI cpython-37m-aarch64-linux-gnu)

# This assumes that pthread will be available on the target system
# (this emulates that the return of the TRY_RUN is a return code "0")
set(THREADS_PTHREAD_ARG "0"
  CACHE STRING "Result from TRY_RUN" FORCE)
